export * from './types'
export { normalizeText } from './dynamic'
export { strategyByKind } from './strategies'
export { scopeOf } from './DescriptorBuilder'
export { DescriptorStore, type DescriptorSummary } from './DescriptorStore'
export { resolveState } from './Scoring'
export { DEFAULT_HEALING, type HealingPolicy } from './Healing'
export { IdentityService } from './IdentityService'
